In [10]:
#QUESTION 1
def maximum(n1,n2,n3):
    if n1>n2 and n1>n3:
        print(f'Maximum value : {n1}')
    elif n2>n1 and n2>n3:
        print(f'Maximum value : {n2}')
    else:
        print(f'Maximum value : {n3}')
n1=int(input("Enter first number : "))
n2=int(input("Enter second number : "))
n3=int(input("Enter third number : "))
maximum(n1,n2,n3)

Enter first number : 7
Enter second number : 5
Enter third number : 3
Maximum value : 7


In [13]:
#QUESTION 2
def area(r):
    circle_area=3.14*r**2
    print(f'Area of a circle : {circle_area}')
r=float(input("Radius : "))
area(r)

Radius : 4
Area of a circle : 50.24


In [4]:
#QUESTION 3
def prime(n):
    for i in range(2,n):
        if n%i==0:
            return False
    else:
        return True
n=int(input("Enter a number : "))
prime(n)

Enter a number : 11


True

In [29]:
#QUESTION 4
def palindrome(string):
    if string==string[::-1]:
        return True
    else:
        return False
string=input("Enter the string : ")
palindrome(string)

Enter the string : wow


True

In [1]:
#QUESTION 5
def sum_of_all(list1):
    sum1=0
    for i in list1:
        sum1+=i
    return sum1
list1=[2,4,6,8,10]
print(list1)
sum_of_all(list1)

[2, 4, 6, 8, 10]


30

In [2]:
#QUESTION 6
def average(list2):
    sum1=0
    for i in list2:
        sum1+=i
    avg=sum1/len(list2)
    return avg
list2=[1,3,5,7,9]
average(list2)

5.0

In [53]:
#QUESTION 7
def kth_largest(list3,k):
    list3.sort(reverse=True)
    print(f'{k}th largest element : {list3[k-1]}' )
list3=[2,6,4,9,1,8]
k=3
print(list3)
kth_largest(list3,k)       

[2, 6, 4, 9, 1, 8]
3th largest element : 6


In [3]:
#QUESTION 8
def sum_of_digits(integer):
    if integer<10:
        return integer
    else:
        return integer%10 + sum_of_digits(integer//10)
integer=1235
sum_of_digits(integer)

11

In [14]:
#QUESTION 9
def power_of_number(base,exp):
    if exp==0:
        return 1
    else:
        for i in range(exp):
            return base*power_of_number(base,exp-1)
base=int(input("Enter base value : "))
exp=int(input("Enter exponent value : "))
powr=power_of_number(base,exp)
print(f'Power of the number : {powr}')

Enter base value : 3
Enter exponent value : 4
Power of the number : 81


In [18]:
#QUESTION 10
def gcd(a,b):
    while b!=0:
        a,b=b,a%b
    return a
a=int(input("Enter first number : "))
b=int(input("Enter second number : "))
print(f"Greatest common divisor of {a} and {b} : {gcd(a,b)}")
    
        

Enter first number : 48
Enter second number : 120
Greatest common divisor of 48 and 120 : 24


In [20]:
#QUESTION 11
import numpy as np
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#QUESTION 12
arr2=np.arange(1,10)
arr2=arr2.reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#QUESTION 13
arr3=np.eye(3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
#QUESTION 14
arr4=np.random.randint(10,101,10)
print(arr4)
print(f"mean : {arr4.mean()}")
print(f"standard deviation : {arr4.std()}")

[ 57  86  28  47  40  24  39  56 100  60]
mean : 53.7
standard deviation : 22.878155520058865


In [38]:
#QUESTION 15
arr5=np.arange(10,21)
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
arr5[:5]

array([10, 11, 12, 13, 14])

In [47]:
#QUESTION 16
arr6=np.arange(2,33,2)
arr6=arr6.reshape(4,4)
arr6

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [50]:
arr6[1]

array([10, 12, 14, 16])

In [52]:
#QUESTION 17
arr7=np.arange(1,6)
arr7


array([1, 2, 3, 4, 5])

In [53]:
arr8=np.arange(6,11)
arr8

array([ 6,  7,  8,  9, 10])

In [54]:
arr=arr7+arr8
arr

array([ 7,  9, 11, 13, 15])

In [67]:
#QUESTION 18
arr9=np.random.rand(10)
arr9

array([0.814989  , 0.26424353, 0.24285677, 0.23116113, 0.68855791,
       0.66483129, 0.72939236, 0.85329087, 0.24836202, 0.16538713])

In [73]:
arr9[arr9<0.5]=0
arr9


array([0.814989  , 0.        , 0.        , 0.        , 0.68855791,
       0.66483129, 0.72939236, 0.85329087, 0.        , 0.        ])